package com.mra.satpro.utilerias;

import com.mra.satpro.R;

/**
 * Created by marianorodriguezabarca on 1/5/19.
 */

public class Escuelas {


    /*public static String arrayEscuelasCarreras[] = {
            "Selecciona una licenciatura",
            "Actuaria Ciudad Universitaria",
            "Actuaria FES Acatlán",
            "Arquitectura Ciudad Universitaria",
            "Arquitectura FES Aragón",
            "Arquitectura FES Acatlán",
            "Arquitectura del Paisaje Ciudad Universitaria",
            "Ciencia de Materiales Sustentables Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Ciencias de la Computación Ciudad Universitaria",
            "Ciencias de la Tierra Ciudad Universitaria",
            "Ciencias de la Tierra UMDI, Juriquilla, Qro",
            "Diseño Industrial FES Aragón",
            "Física Ciudad Universitaria",
            "Física Biomédica Ciudad Universitaria",
            "Geociencias Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Ingeniería Cívil Ciudad Universitaria",
            "Ingeniería Cívil FES Aragón",
            "Ingeniería Cívil FES Acatlán",
            "Ingeniería de Eléctrica - Electrónica Ciudad Universitaria",
            "Ingeniería de Eléctrica - Electrónica FES Aragón",
            "Ingeniería de Minas y Metalurgia Ciudad Universitaria",
            "Ingeniería en Computación Ciudad Universitaria",
            "Ingeniería en Computación FES Aragón",
            "Ingeniería en Telecomunicaciones Sistemas y Electrónica FES Cuautitlán",
            "Ingeniería Geofísica Ciudad Universitaria",
            "Ingeniería Geológica Ciudad Universitaria",
            "Ingeniería Geomática Ciudad Universitaria",
            "Ingeniería Industrial Ciudad Universitaria",
            "Ingeniería Industrial FES Aragón",
            "Ingeniería Industrial FES Cuautitlán",
            "Ingeniería Mecánica Ciudad Universitaria",
            "Ingeniería Mecánica FES Aragón",
            "Ingeniería Mecánica Eléctrica FES Cuautitlán",
            "Ingeniería Petrolera Ciudad Universitaria",
            "Ingeniería Química Ciudad Universitaria",
            "Ingeniería Química FES Cuautitlán",
            "Ingeniería Química FES Zaragoza",
            "Ingeniería Química Metalúrgica Ciudad Universitaria",
            "Matemáticas Ciudad Universitaria",
            "Matemáticas Aplicadas Ciudad Universitaria",
            "Matemáticas Aplicadas y Computación FES Acatlán",
            "Tecnologías para la Información en Ciencias Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Biología Ciudad Universitaria",
            "Biología FES Zaragoza",
            "Biología FES Iztacala",
            "Biología Tlaxcala",
            "Bioquímica Diagnóstica FES Cuautitlán",
            "Ciencias Ambientales Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Cirujano Dentista Ciudad Universitaria",
            "Cirujano Dentista FES Zaragoza",
            "Cirujano Dentista FES Iztacala",
            "Enfermería FES Zaragoza",
            "Enfermería FES Iztacala",
            "Enfermería Escuela Nacional De Enfermería y Obstetricia",
            "Enfermería Tlaxcala",
            "Enfermería y Obstetricia Escuela Nacional De Enfermería y Obstetricia",
            "Farmacia FES Cuautitlán",
            "Físioterapia Escuela Nacional de Estudios Superiores, Unidad León",
            "Ingeniería Agrícola FES Cuautitlán",
            "Ingeniería en Alimentos FES Cuautitlán",
            "Medicina Veterinaria y Zootecnia Ciudad Universitaria",
            "Medicina Veterinaria y Zootecnia FES Cuautitlán",
            "Medico Cirujano Ciudad Universitaria",
            "Medico Cirujano FES Zaragoza",
            "Medico Cirujano FES Iztacala",
            "Odontología Escuela Nacional de Estudios Superiores, Unidad León",
            "Optometría FES Iztacala",
            "Optometría Escuela Nacional de Estudios Superiores, Unidad León",
            "Psicología Ciudad Universitaria",
            "Psicología FES Zaragoza",
            "Psicología FES Iztacala",
            "Psicología Modalidad Abierta Ciudad Universitaria",
            "Psicología Modalidad A Distancia",
            "Psicología Tlaxcala",
            "Química Ciudad Universitaria",
            "Química FES Cuautitlán",
            "Química de Alimentos Ciudad Universitaria",
            "Química Farmacéutico Biológica Ciudad Universitaria",
            "Química Farmacéutico Biológica FES Zaragoza",
            "Química Industrial FES Cuautitlán",
            "Administración Ciudad Universitaria",
            "Administración FES Cuautitlán",
            "Administración Modalidad Abierta Ciudad Universitaria",
            "Administración Modalidad A Distancia",
            "Administración Agropecuaria Escuela Nacional de Estudios Superiores, Unidad León",
            "Antropología Ciudad Universitaria",
            "Ciencias de la Comunicación Ciudad Universitaria",
            "Ciencias de la Comunicación Modalidad Abierta Ciudad Universitaria",
            "Ciencias de la Comunicación (Periodismo) Modalidad A Distancia",
            "Ciencias Políticas y Administración Pública Ciudad Universitaria",
            "Ciencias Políticas y Administración Pública FES Acatlán",
            "Ciencias Políticas y Administración Pública Modalidad Abierta Ciudad Universitaria",
            "Ciencias Políticas y Administración Pública Modalidad A Distancia",
            "Comunicación FES Acatlán",
            "Comunicación y Periodismo FES Aragón",
            "Contaduría Ciudad Universitaria",
            "Contaduría FES Cuautitlán",
            "Contaduría Modalidad Abierta Ciudad Universitaria",
            "Contaduría Modalidad A Distancia",
            "Derecho Ciudad Universitaria",
            "Derecho FES Aragón",
            "Derecho FES Acatlán",
            "Derecho Modalidad Abierta Acatlán",
            "Derecho Modalidad Abierta Ciudad Universitaria",
            "Derecho Modalidad Abierta Aragón",
            "Derecho Modalidad A Distancia",
            "Desarrollo Comunitario para el Envejecimiento Tlaxcala",
            "Desarrollo Territorial Escuela Nacional de Estudios Superiores, Unidad León",
            "Economía Ciudad Universitaria",
            "Economía FES Aragón",
            "Economía FES Acatlán",
            "Economía Modalidad Abierta Ciudad Universitaria",
            "Economía Modalidad Abierta Aragón",
            "Economía Modalidad A Distancia",
            "Economía Industrial Escuela Nacional de Estudios Superiores, Unidad León",
            "Estudios Sociales y Gestión Local Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Geografía Ciudad Universitaria",
            "Geografía Modalidad Abierta Ciudad Universitaria",
            "Informática FES Cuautitlán",
            "Planif. para el Desarrollo Agropecuario FES Aragón",
            "Relaciones Internacionales Ciudad Universitaria",
            "Relaciones Internacionales FES Aragón",
            "Relaciones Internacionales FES Acatlán",
            "Relaciones Internacionales Modalidad Abierta Acatlán",
            "Relaciones Internacionales Modalidad Abierta Ciudad Universitaria",
            "Relaciones Internacionales Modalidad Abierta Aragón",
            "Relaciones Internacionales Modalidad A Distancia",
            "Sociología Ciudad Universitaria",
            "Sociología FES Aragón",
            "Sociología FES Acatlán",
            "Sociología Modalidad Abierta Ciudad Universitaria",
            "Sociología Modalidad A Distancia",
            "Trabajo Social Modalidad A Distancia",
            "Trabajo Social Escuela Nacional de Trabajo Social",
            "Administración de Archivos y Gestión Documental Ciudad Universitaria",
            "Administración de Archivos y Gestión Documental Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Artes Visuales Facultad de Artes y Diseño",
            "Artes Visuales Plantel Taxco, GRO",
            "Arte y Diseño Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Arte y Diseño Plantel Taxco, GRO",
            "Bibliotecologia y Estudios de la Información Ciudad Universitaria",
            "Bibliotecologia y Estudios de la Información Modalidad A Distancia",
            "Canto Escuela Nacional de Música",
            "Composición Escuela Nacional de Música",
            "Desarrollo y Gestión Interculturales Ciudad Universitaria",
            "Desarrollo y Gestión Interculturales Escuela Nacional de Estudios Superiores, Unidad León",
            "Desarrollo y Gestión Interculturales Centro Peninsular en Humanidades y Ciencias Sociales",
            "Diseño Gráfico FES Acatlán",
            "Diseño y Comunicación Visual FES Cuautitlán",
            "Diseño y Comunicación Visual Modalidad A Distancia",
            "Diseño y Comunicación Visual Facultad de Artes y Diseño",
            "Educación Musical Escuela Nacional de Música",
            "Enseñanza de Alemán como Lengua Extranjera Modalidad A Distancia",
            "Enseñanza de Español como Lengua Extranjera Modalidad A Distancia",
            "Enseñanza de Francés como Lengua Extranjera Modalidad A Distancia",
            "Enseñanza de Inglés FES Acatlán",
            "Enseñanza de Inglés como Lengua Extranjera Modalidad A Distancia",
            "Enseñanza de Italiano como Lengua Extranjera Modalidad A Distancia",
            "Estudios Latinoamericanos Ciudad Universitaria",
            "Etnomusicología Escuela Nacional de Música",
            "Filosofía Ciudad Universitaria",
            "Filosofía FES Acatlán",
            "Filosofía Modalidad Abierta Ciudad Universitaria",
            "GeoHistoria Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Historia Ciudad Universitaria",
            "Historia FES Acatlán",
            "Historia Modalidad Abierta Ciudad Universitaria",
            "Historia del Arte Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Instrumentista Escuela Nacional de Música",
            "Lengua y Literaturas Hispánicas Ciudad Universitaria",
            "Lengua y Literaturas Hispánicas FES Acatlán",
            "Lengua y Literaturas Hispánicas Modalidad Abierta Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Alemanas) Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Francesas) Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Inglesas) Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Inglesas) Modalidad Abierta Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Italianas) Ciudad Universitaria",
            "Lengua y Literaturas Modernas (Letras Portuguesas) Ciudad Universitaria",
            "Letras Clásicas Ciudad Universitaria",
            "Lingüistica aplicada Ciudad Universitaria",
            "Literatura Dramática y Teatro Ciudad Universitaria",
            "Literatura Intercultural Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Música y Tecnología Artística Escuela Nacional de Estudios Superiores, Unidad Morelia",
            "Nutriología FES Zaragoza",
            "Pedagogía Ciudad Universitaria",
            "Pedagogía FES Aragón",
            "Pedagogía FES Acatlán",
            "Pedagogía Modalidad Abierta Ciudad Universitaria",
            "Pedagogía Modalidad A Distancia",
            "Piano Escuela Nacional de Música",
            "Traducción Ciudad Universitaria",
            "Licenciatura en Teatro y Actuación"
    };

    public static String arrayEscuelasPuntaje[] = {
            "0",
            "107",
            "102",
            "95",
            "83",
            "84",
            "86",
            "71",
            "108",
            "97",
            "89",
            "94",
            "113",
            "109",
            "81",
            "99",
            "78",
            "81",
            "100",
            "90",
            "93",
            "99",
            "89",
            "75",
            "97",
            "86",
            "96",
            "101",
            "93",
            "81",
            "106",
            "93",
            "78",
            "93",
            "103",
            "90",
            "86",
            "99",
            "104",
            "104",
            "73",
            "59",
            "103",
            "85",
            "89",
            "66",
            "96",
            "70",
            "97",
            "88",
            "87",
            "90",
            "86",
            "80",
            "55",
            "95",
            "81",
            "79",
            "75",
            "79",
            "104",
            "92",
            "113",
            "107",
            "109",
            "74",
            "80",
            "66",
            "102",
            "78",
            "81",
            "72",
            "40",
            "75",
            "108",
            "94",
            "104",
            "105",
            "100",
            "83",
            "94",
            "77",
            "84",
            "82",
            "40",
            "87",
            "104",
            "80",
            "48",
            "97",
            "67",
            "69",
            "56",
            "78",
            "81",
            "89",
            "72",
            "82",
            "82",
            "96",
            "73",
            "68",
            "62",
            "76",
            "56",
            "56",
            "40",
            "50",
            "87",
            "86",
            "83",
            "80",
            "62",
            "44",
            "89",
            "50",
            "96",
            "88",
            "71",
            "65",
            "107",
            "99",
            "90",
            "66",
            "88",
            "61",
            "41",
            "70",
            "60",
            "63",
            "69",
            "52",
            "72",
            "68",
            "41",
            "42",
            "103",
            "57",
            "86",
            "42",
            "65",
            "57",
            "60",
            "71",
            "94",
            "59",
            "45",
            "99",
            "101",
            "87",
            "104",
            "48",
            "43",
            "51",
            "40",
            "67",
            "63",
            "53",
            "89",
            "66",
            "95",
            "70",
            "77",
            "43",
            "100",
            "64",
            "87",
            "82",
            "41",
            "101",
            "81",
            "74",
            "41",
            "60",
            "73",
            "72",
            "65",
            "62",
            "101",
            "94",
            "102",
            "70",
            "74",
            "91",
            "72",
            "67",
            "65",
            "75",
            "77",
            "48",
            "107",
            "98"
    };

    public static int[] arrayImagenEscuela = {
                        0,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam
    };


    public static String[] arrayEscuelasArea = {
            "",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 3: Ciencias Sociales",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes",
            "Área 4: Humanidades y Artes"
    };*/


    public static String[] arrayAreas = {
            "Selecciona un área de estudio",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 3: Ciencias Sociales",
            "Área 4: Humanidades y Artes"

    };

    public static String[] arrayClasificacionAreas = {
            "",
            "Área 1: Ciencias Físico Matemáticas y de las Ingenierias",
            "Área 2: Ciencias Biológicas, Quimicas y de la Salud",
            "Área 3: Ciencias Sociales",
            "Área 4: Humanidades y Artes"
    };

    public static int[] arrayImagenClasificacionAreas = {
            0,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam,
            R.drawable.unam
    };


}


