package com.mra.satpro.utilerias;

import com.mra.satpro.R;

/**
 * Created by mariano.rodriguez on 04/06/2018.
 */
public class TemarioGlobal {

    public static int nombreImagenEspanol[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasEspanol[] = {
            "Función Apelativa.",
            "Función Referencial.",
            "Función Poética. ",
            "Discurso narrativo.",
            "Discurso descriptivo. ",
            "Discurso argumentativo.",
            "Oración simple.",
            "Oración compuesta. ",
            "Uso del Sujeto.",
            "Núcleo del sujeto.",
            "Complementos Circunstanciales.",
            "Complemento indirecto.",
            "Algunos errores comunes al redactar.",
            "Se escribe con b.",
            "Se escribe con v.",
            "Se escribe con c.",
            "Se escribe con s.",
            "Se escribe con h.",
            "Se escribe con g.",
            "Se escribe con j.",
            "Se escribe con ll.",
            "Se escribe con y.",
  "Copretérito",
  "Nexo",
  "Orden de ideas",
  "Texto informativo",
  "Ilustraciones",
  "Adverbio",
  "Puntos suspensivos",
  "Los conectores",
  "Tipos de puntos",
  "Ficha bibliográfica",
  "Índice",
  "Título",
  "Tipo de letra",
  "Gráficas",
  "Explicación",
  "Orden cronológico",
  "Tema",
  "Cita textual y paráfrasis",
  "Modificadores",
  "Enunciados Unimembres",
  "Enunciado bimembre"
    };


    public static String nombreVideoEspanol[] = {
            "funcion_apelativa.mp4",
            "funcion_referencial.mp4",
            "funcion_Poetica.mp4",
            "discurso_narrativo.mp4",
            "discurso_descriptivo.mp4",
            "discurso_argumentativo.mp4",
            "oracion_simple.mp4",
            "oracion_compuesta.mp4",
            "uso_del_sujeto.mp4",
            "nucleo_del_sujeto.mp4",
            "complementos_circunstanciales.mp4",
            "complemento_indirecto.mp4",
            "algunos_errores_comunes_al_redactar.mp4",
            "se_escribe_con_b.mp4",
            "se_escribe_con_v.mp4",
            "se_escribe_con_c.mp4",
            "se_escribe_con_s.mp4",
            "se_escribe_con_h.mp4",
            "se_escribe_con_g.mp4",
            "se_escribe_con_j.mp4",
            "se_escribe_con_ll.mp4",
            "se_escribe_con_y.mp4",

            "copreterito_espanol_comipems.mp4",
            "nexo_espanol_comipems.mp4",
            "orden_de_ideas_espanol_comipems.mp4",
            "texto_informativo_espanol_comipems.mp4",
            "ilustraciones_espanol_comipems.mp4",
            "adverbio_espanol_comipems.mp4",
            "puntos_suspensivos_espanol_comipems.mp4",
            "los_conectores_espanol_comipems.mp4",
            "tipos_de_puntos_espanol_comipems.mp4",
            "ficha_bibliográfica_comipems_espanol.mp4",
            "indice_comipems_espanol.mp4",
            "titulo_comipems_espanol.mp4",
            "tipo_de_letra_comipems_espanol.mp4",
            "graficas_comipems_espanol.mp4",
            "explicacion_comipems_espanol.mp4",
            "orden_cronologico_comipems_espanol.mp4",
            "tema_comipems_espanol.mp4",
            "cita_textual_comipems_espanol.mp4",
            "modificadores_comipems_espanol.mp4",
            "enunciados_unimembres_cimipems_espanol.mp4",
            "enunciado_bimembre.mp4"
    };


    //HISTORIA DE MEXICO

    public static int nombreImagenHisMex[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasHisMex[] = {
            "Asentamiento Tres Zapotes",
            "Las Audiencias",
            "La civilización maya.",
            "Caída de la gran ciudad de Tenochtitlán.",
            "Juan de Grijalva.",
            "Reformas Borbónicas.",
            "Organización de la Independencia.",
            "Virreinato de Nueva España.",
            "Dominicos.",
            "Primera República Federal.",
            "Batalla de la Angostura.",
            "Ley Lerdo.",
            "Benito Juarez.",
            "El Plan de Tuxtepec.",
            "Luis Echeverría.",
            "Neoliberalismo.",
            "El TLCAN.",
            "Carlos Salinas de Gortari."
    };

    public static int idVideoHisMex[] = {
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17
    };

    public static String nombreVideoHisMex[] = {
            "asentamiento_tres_zapotes.mp4",
            "las_audiencias.mp4",
            "la_civilizacion_maya.mp4",
            "juan_de_grijalva.mp4",
            "caida_de_tenochtitlan.mp4",
            "reformas_borbonicas.mp4",
            "organizacion_de_la_independencia.mp4",
            "virreinato_de_nueva_espana.mp4",
            "dominicos.mp4",
            "primera_república_federal.mp4",
            "batalla_de_la_angostura.mp4",
            "ley_lerdo.mp4",
            "benito_juarez.mp4",
            "el_plan_de_tuxtepec.mp4",
            "luis_echeverria.mp4",
            "neoliberalismo.mp4",
            "el_tlcan.mp4",
            "carlos_salinas_de_gortari.mp4"
    };


    //HIS UNIVERSAL

    //HISTORIA DE UNIVERSAL

    public static int nombreImagenHisUniv[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasHisUniv[] = {
            "Enciclopedismo",
            "Newton, Descartes y Smith.",
            "El liberalismo económico.",
            "Adam Smith.",
            "La abolición de la esclavitud en las colonias.",
            "La imposición de aranceles a las colonias.",
            "Thomas Jefferson.",
            "La Bastilla. ",
            "La Primera República Francesa.",
            "Lista de causas de la Revolución Industrial.",
            "Gran Alianza",
            "Doctrina Monroe.",
            "Los borbones.",
            "La dominación Francesa sobre España",
            "Las Guerras Napoleónicas.",
            "El federalismo.",
            "Socialismo.",
            "Congreso de Viena.",
            "Víctor Manuel II",
            "El Imperialismo en el Siglo XIX.",
            "Marie Curie.",
            "Nacionalismo.",

            "Edad moderna",
            "Renacimiento y el Humanismo",
            "Tratado de Tordesilla",
            "Ilustración o Iluminismo",
            "El derecho divino",
            "Feudalismo",
            "Colonialismo",
            "Fernando de Magallanes",
            "Renacimiento",
            "Martín Lutero",
            "Las trece colonias.",
            "Toma de la Bastilla.",
            "Independencia Hispanoamérica.",
            "Revolución Industrial.",
            "Las guerras napoleónicas.",
            "Imperialismo.",
            "Primera Guerra Mundial.",
            "Tratado de Versalles.",
            "Revolución francesa.",
            "El Nacionalismo.",
            "Revolución rusa.",
            "Nacional Socialista.",
            "El capitalismo.",
            "Segunda Revolución Industrial.",
            "Los aliados.",
            "Conflicto del Golfo Pérsico.",
            "Neoliberalismo.",
            "El muro de Berlín.",
            "Sistema socialista.",
            "Elementos Segunda Revolución Industrial."
    };



    public static String nombreVideoHisUniv[] = {
            "enciclopedismo.mp4",
            "newton_descartes_smith_lavoisier.mp4",
            "el_liberalismo_economico.mp4",
            "adam_smith.mp4",
            "la_abolicion_de_la_esclavitud_en_las_colonias.mp4",
            "la_imposición_de_aranceles_a_las_colonias.mp4",
            "thomas_jefferson.mp4",
            "la_bastilla.mp4",
            "la_primera_republica_francesa.mp4",
            "lista_de_causas_de_la_revolución_industrial.mp4",
            "gran_alianza.mp4",
            "doctrina_monroe.mp4",
            "los_borbones.mp4",
            "la_dominación_francesa-sobre_españa.mp4",
            "las_guerras_napoleónicas.mp4",
            "el_federalismo.mp4",
            "socialismo.mp4",
            "congreso_de_viena.mp4",
            "víctor_manuel_II.mp4",
            "el_imperialismo_en_el_siglo_XIX.mp4",
            "marie_curie.mp4",
            "nacionalismo.mp4",

            "edad_moderna.mp4",
            "renacimiento_y_humanismo.mp4",
            "tratado_de_tordesilla.mp4",
            "ilustracion_o_iluminismo.mp4",
            "el_derecho_divino.mp4",
            "feudalismo.mp4",
            "colonialismo.mp4",
            "fernando_de_magallanes.mp4",
            "renacimiento.mp4",
            "martin_lutero.mp4",
            "las_trece_colonias.mp4",
            "toma_de_la_bastilla.mp4",
            "independencia_hispanoamerica.mp4",
            "revolucion_industrial.mp4",
            "las_guerras_napoleonicas.mp4",
            "imperialismo.mp4",
            "primera_guerra_mundial.mp4",
            "tratado_de_versalles.mp4",
            "revolucion_francesa.mp4",
            "el_nacionalismo.mp4",
            "revolucion_rusa.mp4",
            "nacional_socialista.mp4",
            "el_capitalismo.mp4",
            "segunda_revolucion_industrial.mp4",
            "los_aliados.mp4",
            "conflicto_del_golfo_persico.mp4",
            "neoliberalismo.mp4",
            "el_muro_de_berlin.mp4",
            "sistema_socialista.mp4",
            "elementos_segunda_revolucion_industrial.mp4"
    };


    //GEOGRAFIA DE UNIVERSAL

    public static int nombreImagenGeo[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasGeoUniv[] = {
            "Migrante.",
            "Globo terráqueo.",
            "Paralelos y meridianos.",
            "Organización Mundial del Comercio.",
            "Mareas.",
            "Subducción.",
            "Los Alpes.",
            "Pirineos.",
            "Amazonas.",
            "Monte Atlas.",
            "Espacio terrestre.",
            "Exosfera.",
            "Mapa.",
            "Internet.",
            "País multicultural.",
            "Escala.",
            "Patrimonio cultural.",
            "Etnia.",
            "Espacios de soberanía nacional.",
            "Conflicto entre palestinos e israelíes."
    };



    public static String nombreVideoGeoUniv[] = {
            "migrante.mp4",
            "globo_terraqueo.mp4",
            "paralelos_y_meridianos.mp4",
            "organizacion_mundial_del_comercio.mp4",
            "mareas.mp4",
            "subduccion.mp4",
            "los_alpes.mp4",
            "pirineos.mp4",
            "amazonas.mp4",
            "monte_atlas.mp4",
            "espacio_terrestre.mp4",
            "exosfera.mp4",
            "mapa.mp4",
            "internet.mp4",
            "pais_multicultural.mp4",
            "escala.mp4",
            "patrimonio_cultural.mp4",
            "etnia.mp4",
            "espacios_de_soberania_nacional.mp4",
            "conflicto_entre_palestinos_e_israelies.mp4"
    };

    //RAZ MATEMATICO

    public static int nombreImagenRazMate[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasRazMate[] = {
            "Imaginación espacial.",
            "Series numéricas agrupadas.",
            "Series numéricas descendentes.",
            "Series numéricas ascendentes.",
            "Regla de tres.",
            "Estrategias de razonamiento.",
            "Series formadas por una ley."
    };



    public static String nombreVideoRazMate[] = {
            "imaginacion_espacial.mp4",
            "series_numericas_agrupadas.mp4",
            "series_numericas_descendentes.mp4",
            "series_numericas_ascendentes.mp4",
            "regla_de_tres.mp4",
            "estrategias_de_razonamiento.mp4",
            "series_formadas_por_una_ley.mp4"


    };

    //GEO DE MEXICO


    public static int nombreImagenGeoMex[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasGeoMex[] = {
            "El meridiano cero.",
            "Tectónica de placas.",
            "Plegamiento.",
            "Océano Pacífico.",
            "Los continentes.",
            "Indicadores socioeconómicos.",
            "Factores del clima.",
            "El río Colorado.",
            "África.",
            "Asia.",
            "Trópico de Cáncer.",

            "Puerto de Veracruz.",
            "Usumacinta, Suchiate.",
            "Sonda de Campeche.",
            "Popocatépetl.",
            "Producción maderable.",
            "Rio Usumacinta y Mayo.",
            "Mixtecas, Zapotecos.",
            "Golfo de México.",
            "Zona del Bajío.",
            "Eje Neo volcánico."
    };



    public static String nombreVideoGeoMex[] = {
            "el_meridiano_cero.mp4",
            "Tectonica_de_placas.mp4",
            "plegamiento.mp4",
            "oceano_Pacifico.mp4",
            "los_continentes.mp4",
            "indicadores_socioeconomicos.mp4",
            "factores_del_clima.mp4",
            "el_rio_colorado.mp4",
            "africa.mp4",
            "asia.mp4",
            "tropico_de_cancer.mp4",

            "puerto_de_veracruz.mp4",
            "usumacinta_suchiate.mp4",
            "sonda_de_campeche.mp4",
            "popocatepetl.mp4",
            "produccion_maderable.mp4",
            "rio_usumacinta_y_mayo.mp4",
            "mixtecas_zapotecos.mp4",
            "golfo_de_mexico.mp4",
            "zona_del_bajio.mp4",
            "eje_neo_volcanico.mp4"
    };


    //FISICA


    public static int nombreImagenFisica[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasFisica[] = {
            "Problema Magnitud de un vector.",
            "Sistema Internacional.",
            "Km/h a m/s",
            "Problema Velocidad media.",
            "Problema Distancia.",
            "Problema Tiempo y velocidad.",
            "Problema Altura máxima.",
            "Problemas de energía cinetica.",
            "Problema Centígrados a Fahrenheit.",
            "Problema Fahrenheit a Centígrados.",
            "Efecto fotoeléctrico.",
            "Capacidad calorífica.",
            "Difracción.",

            "Relación de magnitudes.",
            "Tiro parabólico.",
            "Movimiento rectilíneo uniforme.",
            "Movimiento Uniformemente Acelerado.",
            "Uniformemente acelerado.",
            "Magnitud escalar.",
            "Movimiento Pendular.",
            "Magnitud vectorial.",
            "Velocidad.",
            "Galileo Galilei.",
            "Aceleración.",
            "Leyes de Newton."
    };



    public static String nombreVideoFisica[] = {
            "problema_magnitud_de_un_vector.mp4",
            "sistema_internacional.mp4",
            "km_h_a_m_s.mp4",
            "problema _velocidad_media.mp4",
            "problema_distancia.mp4",
            "problema_tiempo_y_velocidad.mp4",
            "problema _altura_maxima.mp4",
            "problemas_de_energia_cinetica.mp4",
            "problema_centigrados_a_fahrenheit.mp4",
            "problema_fahrenheit_a_centigrados.mp4",
            "efecto_fotoelectrico.mp4",
            "capacidad_calorifica.mp4",
            "difraccion.mp4",

            "relacion_de_magnitudes.mp4",
            "tiro_parabolico.mp4",
            "movimiento_rectilineo_uniforme.mp4",
            "movimiento_uniformemente_acelerado.mp4",
            "uniformemente_acelerado.mp4",
            "magnitud_escalar.mp4",
            "movimiento_pendular.mp4",
            "magnitud_vectorial.mp4",
            "velocidad.mp4",
            "galileo_galilei.mp4",
            "formula_de_la_aceleracion.mp4",
            "leyes_de_newton.mp4"
    };


    //RAZ VERBAL


    public static int nombreImagenRazVerbal[] = {
            R.mipmap.play,
            //R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasRazVerbal[] = {
            "Analogía.",
            //"Significado opuesto.",
            "Antónimos.",
            "Sinónimo.",
            "Análisis critico",
            "Conclusión.",
            "Idea secundaria.",
            "Idea principal.",
            "Contenido del texto.",
            "Hechos."
    };



    public static String nombreVideoRazVerbal[] = {
            "analogIa.mp4",
            //"significado_opuesto.mp4",
            "antonimos.mp4",
            "sinonimo.mp4",
            "analisis_critico.mp4",
            "conclusion.mp4",
            "idea_secundaria.mp4",
            "idea_principal.mp4",
            "contenido_del_texto.mp4",
            "hechos.mp4"
    };


    //QUIMICA


    public static int nombreImagenQuimica[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasQuimica[] = {
            "Enlace iónico y covalente.",
            "La polaridad.",
            "Cation.",
            "Mol.",
            "Alcanos.",
            "Enlaces pi.",
            "Entalpía.",
            "Combustión.",
            "Los ésteres.",

            "Química.",
            "Propiedades cualitativas.",
            "Método científico.",
            "Propiedades químicas.",
            "Ley de la Conservación de la Materia.",
            "Mezcla.",
            "Una mezcla heterogénea.",
            "Coloide.",
            "Disolución.",
            "Decantación.",
            "Cristalización.",
            "Neutrones.",
            "Peso atómica.",
            "Átomo.",
            "Ion.",
            "Protón.",
            "Electrón.",
            "Estructuras de Lewis.",
            "Tabla periódica.",
            "Electrostático.",
            "La electronegatividad.",
            "Reacción.",
            "Coeficiente.",
            "Reacción química.",
            "Subíndice.",
            "Ecuación química.",
            "Escala PH."
    };



    public static String nombreVideoQuimica[] = {
            "enlace_ionico_y_covalente.mp4",
            "la_polaridad.mp4",
            "cation.mp4",
            "mol.mp4",
            "alcanos.mp4",
            "enlaces pi.mp4",
            "entalpia.mp4",
            "combustion.mp4",
            "los esteres.mp4",

            "quImica.mp4",
            "propiedades_cualitativas.mp4",
            "metodo_cientifico.mp4",
            "propiedades_quimicas.mp4",
            "ley_de_la_conservacion_de_la_materia.mp4",
            "mezcla.mp4",
            "una_mezcla_heterogenea.mp4",
            "coloide.mp4",
            "disolucion.mp4",
            "decantacion.mp4",
            "cristalizacion.mp4",
            "neutrones.mp4",
            "peso_atomica.mp4",
            "atomo.mp4",
            "ion.mp4",
            "proton.mp4",
            "electron.mp4",
            "estructuras_de_lewis.mp4",
            "tabla_periodica.mp4",
            "electrostatico.mp4",
            "la_electronegatividad.mp4",
            "reaccion.mp4",
            "coeficiente.mp4",
            "reaccion_quimica.mp4",
            "subindice.mp4",
            "ecuacion_quimica.mp4",
            "escala_ph.mp4"
    };


    //MATEMATICAS


    public static int nombreImagenMatematicas[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasMatematicas[] = {
            "Simplificando.",
            "Sustituyendo valores.",
            "Funciones.",
            "Más ejemplos.",
            "Sumas algebraicas.",
            "Restas algebraicas.",
            "Producto algebraico.",
            "División algebraica.",
            "Simplificando raíces cuadradas.",
            "Binomio cuadrado.",
            "Binomio al cubo.",
            "Factorización.",
            "Ecuación de primer grado.",
            "Sistema de ecuaciones.",
            "Sistema de tres ecuaciones.",
            "Funciones.",
            "Logaritmos.",
            "Grados a radianes.",
            "Radianes a grados.",
            "Derivadas.",
            "Integral.",
            "Evaluar integrales.",
            "Evaluar expresiones.",
            "Desigual.",
            "Trigonometría triangulo rectángulo.",
            "Circulo.",
            "Calculo de ángulos.",
            "Promedio:",
            "Mediana.",
            "Desviación estándar.",

            "Raíz cuadrada.",
            "Números primos.",
            "Ecuaciones algebraicas.",
            "Factorización.",
            "Regla de tres.",
            "Más ejemplos de la regla de tres.",
            "Notación científica.",
            "Multiplicación con decimales.",
            "Número decimal por número entero.",
            "Números enteros.",
            "Solución de operaciones.",
            "Proporción.",
            "Operaciones de fracciones.",
            "Porcentaje.",
            "Multiplicación de potencias",
            "División de potencias de igual base.",
            "Multiplicación de potencias de igual exponente.",
            "Calculo de ángulos.",
            "Binomios."
    };



    public static String nombreVideoMatematicas[] = {
            "Simplificando.mp4",
            "sustituyendo_valores.mp4",
            "funciones_uno.mp4",
            "mas_ejemplos.mp4",
            "sumas_algebraicas.mp4",
            "restas_algebraicas.mp4",
            "producto_algebraico.mp4",
            "division_algebraica.mp4",
            "simplificando_raices_cuadradas.mp4",
            "binomio_cuadrado.mp4",
            "binomio_al_cubo.mp4",
            "factorizacion.mp4",
            "ecuacion_de_primer_grado.mp4",
            "sistema_de_ecuaciones.mp4",
            "sistema_de_tres_ecuaciones.mp4",
            "funciones.mp4",
            "logaritmos.mp4",
            "grados_a_radianes.mp4",
            "radianes_a_grados.mp4",
            "derivadas.mp4",
            "integral.mp4",
            "evaluar_integrales.mp4",
            "evaluar_expresiones.mp4",
            "desigual.mp4",
            "trigonometria_triangulo_rectangulo.mp4",
            "circulo.mp4",
            "calculo_de_angulos.mp4",
            "promedio.mp4",
            "mediana.mp4",
            "desviacion_estandar.mp4",

            "raiz_cuadrada.mp4",
            "numeros_primos.mp4",
            "ecuaciones_algebraicas.mp4",
            "factorizacion.mp4",
            "regla_de_tres.mp4",
            "mas_ejemplos_de_la_regla_de_tres.mp4",
            "notacion_cientifica.mp4",
            "multiplicacion_con_decimales.mp4",
            "numero_decimal_por_numero_entero.mp4",
            "numeros_enteros.mp4",
            "solucion_de_operaciones.mp4",
            "proporcion.mp4",
            "operaciones_de_fracciones.mp4",
            "porcentaje.mp4",
            "multiplicacion_de_potencias.mp4",
            "division_de_potencias_de_igual_base.mp4",
            "multiplicacion_de_potencias_de_igual_exponente.mp4",
            "calculo_de_angulos.mp4",
            "binomios.mp4"
    };


    //BIOLOGIA


    public static int nombreImagenBiologia[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,

            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play
    };

    public static String temasBiologia[] = {
            "Robert Hooke.",
            "Robert Brown.",
            "Carbohidratos.",
            "ATP.",
            "Las ramas de la Biología.",
            "Células heterótrofas.",
            "Respiración aeróbica y fotosíntesis.",
            "El núcleo.",
            "Los fósiles.",
            "Mutación.",
            "Difusión.",
            "Respiración.",
            "Cadena alimenticia.",
            "Productores.",
            "Mimetismo.",
            "Hospedero.",
            "Cloroplastos.",
            "Difusión facilitada.",
            "ARN.",
            "ADN.",
            "Metabolismo celular.",

            "Citología.",
            "Carbono.",
            "Evolución.",
            "Creacionismo.",
            "J. Lamarck",
            "Biodiversidad.",
            "Ecología.",
            "Fotosíntesis.",
            "Tallo.",
            "Oxígeno - ATP.",
            "Respiración aerobia.",
            "La fermentación.",
            "Ciclo biogeoquímico.",
            "Organismos fotosintéticos.",
            "Nutrición.",
            "Cadena trófica.",
            "Quimiosintética.",
            "Efecto invernadero.",
            "Organismos pluricelulares.",
            "Teoria de Darwin.",
            "Capacidad Homeostática.",
            "Reproducción.",
            "Ciclo celular.",
            "Mitosis.",
            "Gemación."
    };



    public static String nombreVideoBiologia[] = {
            "robert_kooke.mp4",
            "robert_brown.mp4",
            "carbohidratos.mp4",
            "atp.mp4",
            "las_ramas_de_la_biologia.mp4",
            "celulas_heterotrofas.mp4",
            "respiracion_aerobica_y_fotosintesis.mp4",
            "el_nucleo.mp4",
            "los_fosiles.mp4",
            "mutacion.mp4",
            "difusion.mp4",
            "respiracion.mp4",
            "cadena_alimenticia.mp4",
            "productores.mp4",
            "mimetismo.mp4",
            "hospedero.mp4",
            "cloroplastos.mp4",
            "difusion_facilitada.mp4",
            "arn.mp4",
            "adn.mp4",
            "metabolismo_celular.mp4",

            "citologia.mp4",
            "carbono.mp4",
            "evolucion.mp4",
            "creacionismo.mp4",
            "j_lamarck.mp4",
            "biodiversidad.mp4",
            "ecologia.mp4",
            "fotosintesis.mp4",
            "tallo.mp4",
            "oxigeno_atp.mp4",
            "respiracion_aerobia.mp4",
            "la_fermentacion.mp4",
            "ciclo_biogeoquimico.mp4",
            "organismos_fotosinteticos.mp4",
            "nutricion.mp4",
            "cadena_trofica.mp4",
            "quimiosintetica.mp4",
            "efecto_invernadero.mp4",
            "organismos_pluricelulares.mp4",
            "teoria_de_darwin.mp4",
            "capacidad_homeostatica.mp4",
            "reproduccion.mp4",
            "ciclo_celular.mp4",
            "mitosis.mp4",
            "gemacion.mp4"
    };


    //FILOSOFIA
    public static int nombreImagenFilosofia[] = {
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play,
            R.mipmap.play

    };

    public static String temasFilosofia[] = {
            "Platón.",
            "Aristóteles.",
            "Descartes.",
            "Heráclito.",
            "Grecia.",
            "Racionalidad.",
            "Anaximandro.",
            "Parménides.",
            "Empédocles.",
            "Sofistas.",
            "Mayéutico.",
            "Estética.",
            "Ética.",
            "Ontología.",
            "Pragmatismo.",
            "Realismo.",
            "Fenomenología.",
            "Positivismo.",
            "Inferencias no válidas.",
            "Disyunción.",
            "Condicional."
    };



    public static String nombreVideoFilosofia[] = {
            "platon.mp4",
            "aristoteles.mp4",
            "descartes.mp4",
            "heraclito.mp4",
            "grecia.mp4",
            "racionalidad.mp4",
            "anaximandro.mp4",
            "parmenides.mp4",
            "empedocles.mp4",
            "sofistas.mp4",
            "mayeutico.mp4",
            "estetica.mp4",
            "etica.mp4",
            "ontologia.mp4",
            "pragmatismo.mp4",
            "realismo.mp4",
            "fenomenologia.mp4",
            "positivismo.mp4",
            "inferencias_no_validas.mp4",
            "disyuncion.mp4",
            "condicional.mp4"
    };

}
